from factories.hypothesis_factory import create_hypothesis


def reason_from_findings(findings):
    """
    Generate competing investigation hypotheses based on
    the category of each ORION finding.
    """

    hypotheses = []
    processed_categories = set()

    for finding in findings:
        category = str(
            getattr(finding, "category", "")
        ).strip()

        if not category:
            continue

        #
        # Avoid generating identical hypothesis sets for
        # every finding in the same evidence category.
        #
        if category in processed_categories:
            continue

        processed_categories.add(category)

        if category == "Malware":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Malicious executable activity",
                        explanation=(
                            "The detected file or executable may "
                            "represent genuine malware execution "
                            "on the affected endpoint."
                        ),
                        confidence=70,
                    ),
                    create_hypothesis(
                        title="False-positive malware detection",
                        explanation=(
                            "The detected file may be legitimate "
                            "software incorrectly classified as "
                            "malicious."
                        ),
                        confidence=30,
                    ),
                    create_hypothesis(
                        title="Authorized security test artifact",
                        explanation=(
                            "The malware detection may have been "
                            "generated by an approved simulation, "
                            "test payload, or security exercise."
                        ),
                        confidence=20,
                    ),
                ]
            )

        elif category == "Process":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Malicious command execution",
                        explanation=(
                            "The observed process activity may "
                            "represent attacker-controlled command "
                            "or script execution."
                        ),
                        confidence=60,
                    ),
                    create_hypothesis(
                        title="Legitimate administrative activity",
                        explanation=(
                            "The process execution may have been "
                            "performed by an authorized administrator "
                            "or automation workflow."
                        ),
                        confidence=35,
                    ),
                    create_hypothesis(
                        title="Authorized security testing",
                        explanation=(
                            "The observed execution may be part of "
                            "an approved security assessment or "
                            "simulation."
                        ),
                        confidence=20,
                    ),
                ]
            )

        elif category == "Identity":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Compromised user account",
                        explanation=(
                            "The identity activity may indicate "
                            "unauthorized use of valid credentials."
                        ),
                        confidence=60,
                    ),
                    create_hypothesis(
                        title="Legitimate user activity",
                        explanation=(
                            "The observed identity activity may "
                            "represent expected user behaviour."
                        ),
                        confidence=35,
                    ),
                    create_hypothesis(
                        title="Credential or access anomaly",
                        explanation=(
                            "The activity may represent unusual "
                            "authentication behaviour requiring "
                            "additional identity validation."
                        ),
                        confidence=45,
                    ),
                ]
            )

        elif category == "Endpoint":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Endpoint compromise",
                        explanation=(
                            "The affected endpoint may contain "
                            "suspicious or attacker-controlled "
                            "activity."
                        ),
                        confidence=50,
                    ),
                    create_hypothesis(
                        title="Benign endpoint activity",
                        explanation=(
                            "The endpoint evidence may be associated "
                            "with legitimate system or user activity."
                        ),
                        confidence=30,
                    ),
                ]
            )

        elif category == "File":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Malicious file artifact",
                        explanation=(
                            "The observed file or hash may be "
                            "associated with malicious activity."
                        ),
                        confidence=55,
                    ),
                    create_hypothesis(
                        title="Benign file artifact",
                        explanation=(
                            "The observed file may be legitimate "
                            "and unrelated to compromise."
                        ),
                        confidence=30,
                    ),
                ]
            )

        elif category == "Infrastructure":
            hypotheses.extend(
                [
                    create_hypothesis(
                        title="Cloud-hosted reconnaissance",
                        explanation=(
                            "Hosted infrastructure may be supporting "
                            "externally initiated reconnaissance."
                        ),
                        confidence=40,
                    ),
                    create_hypothesis(
                        title="Legitimate cloud service activity",
                        explanation=(
                            "The infrastructure may belong to an "
                            "approved cloud provider, vendor, scanner, "
                            "or business service."
                        ),
                        confidence=30,
                    ),
                    create_hypothesis(
                        title="Security testing activity",
                        explanation=(
                            "The infrastructure may be associated "
                            "with authorized vulnerability testing."
                        ),
                        confidence=20,
                    ),
                ]
            )

    return hypotheses
